<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE neuro_triggers
[
<!ELEMENT neuro_triggers (neuro_trigger+)>
<!ATTLIST neuro_triggers name CDATA #REQUIRED>
<!ELEMENT neuro_trigger (state+)>
<!ATTLIST neuro_trigger name CDATA #REQUIRED>
<!ELEMENT state (item+)>
<!ATTLIST state name CDATA #REQUIRED>
<!ELEMENT item (#PCDATA)>
<!ATTLIST item word CDATA #REQUIRED>
<!ATTLIST item weight CDATA #REQUIRED>
]>

<neuro_triggers name="Cameras">
  
    <neuro_trigger name="Color">
        <state name="Black">
            <item word="Black" weight="1"></item>
            <item word="Ebony" weight="1"></item>
            <item word="Nighthawk" weight="1"></item>
            <item word="Graphite" weight="1"></item>
        </state>
        <state name="Red">
            <item word="Red" weight="1"></item>
            <item word="Ruby" weight="1"></item>
            <item word="Merlot" weight="1"></item>
            <item word="Redfire" weight="1"></item>
            <item word="Rallye" weight="1"></item>
            <item word="Redrock" weight="1"></item>
        </state>
        <state name="Pink">
            <item word="Pink" weight="1"></item>
        </state>
        <state name="White">
            <item word="White" weight="1"></item>
            <item word="Diamond" weight="1"></item>
            <item word="Opal" weight="1"></item>
        </state>
        <state name="Gray">
            <item word="Gray" weight="1"></item>
            <item word="Grey" weight="1"></item>
            <item word="Granite" weight="1"></item>
            <item word="Carbon" weight="1"></item>
            <item word="Chrome" weight="1"></item>
            <item word="Charcoal" weight="1"></item>
        </state>
        <state name="Purple">
            <item word="Purple" weight="1"></item>
            <item word="Radish" weight="1"></item>
            <item word="Plum" weight="1"></item>
        </state>
        <state name="Tan">
            <item word="Tan" weight="1"></item>
            <item word="Champagne" weight="1"></item>
            <item word="Bronze" weight="1"></item>
            <item word="Brown" weight="1"></item>
        </state>
        <state name="Silver">
            <item word="Silver" weight="1"></item>
            <item word="Frost" weight="1"></item>
            <item word="Titanium" weight="1"></item>
        </state>
        <state name="Blue">
            <item word="Blue" weight="1"></item>
            <item word="Water" weight="1"></item>
        </state>
        <state name="Green">
            <item word="Green" weight="1"></item>
        </state>
        <state name="Orange">
            <item word="Orange" weight="1"></item>
        </state>
    </neuro_trigger>
    
    <neuro_trigger name="Manufacturer">
        <state name="Canon">
            <item word="Canon" weight="1"></item>
            <item word="Cannon" weight="1"></item>
            <item word="EOS" weight="1"></item>
            <item word="Rebel" weight="1"></item>
            <item word="PowerShot" weight="1"></item>
        </state>
        <state name="Casio">
            <item word="Casio" weight="1"></item>
            <item word="EXILIM" weight="1"></item>
        </state>
        <state name="FUJIFILM">
            <item word="FUJIFILM" weight="1"></item>
            <item word="FUJI" weight="0.1"></item>
            <item word="FinePix" weight="0.1"></item>
        </state>
        <state name="GE" >
            <item word="GE" weight="1"></item>
            <item word="General" weight="0.5"></item>
            <item word="Electric" weight="0.5"></item>
        </state>
        <state name="HP" >
            <item word="HP" weight="1"></item>
            <item word="H-P" weight="1"></item>
            <item word="Hewlett-Packard" weight="1"></item>
            <item word="Hewlett" weight="0.5"></item>
            <item word="Packard" weight="0.5"></item>
        </state>
        <state name="Insignia">
            <item word="Insignia" weight="1"></item>
        </state>
        <state name="Kodak">
            <item word="Kodak" weight="1"></item>
            <item word="Codak" weight="1"></item>
            <item word="EasyShare" weight="1"></item>
        </state>
        <state name="Nikon">
            <item word="Nikon" weight="1"></item>
            <item word="Nicon" weight="1"></item>
            <item word="Nickon" weight="1"></item>
            <item word="Coolpix" weight="1"></item>
        </state>
        <state name="Olympus">
            <item word="Olympus" weight="1"></item>
            <item word="Stylus" weight="1"></item>
        </state>
        <state name="Panasonic">
            <item word="Panasonic" weight="1"></item>
            <item word="Lumix" weight="1"></item>
        </state>
        <state name="PENTAX">
            <item word="PENTAX" weight="1"></item>
            <item word="Optio" weight="1"></item>
        </state>
        
        <state name="Samsung">
            <item word="Samsung" weight="1"></item>
            <item word="Samsun" weight="1"></item>
        </state>
        <state name="Sony">
            <item word="Sony" weight="1"></item>
            <item word="Cyber-Shot" weight="1"></item>
            <item word="Cyber" weight="1"></item>
        </state>
        <state name="Vivitar">
            <item word="Vivitar" weight="1"></item>
        </state>
        <state name="Acer">
            <item word="acer" weight="1"></item>
        </state>
        <state name="Apple">
            <item word="apple" weight="1"></item>
        </state>
        <state name="Asus">
            <item word="asus" weight="1"></item>
        </state>
        <state name="Dell">
            <item word="dell" weight="1"></item>
        </state>
        <state name="Lenovo">
            <item word="lenovo" weight="1"></item>
        </state>
        <state name="Google">
            <item word="google" weight="1"></item>
        </state>
        <state name="Amazon">
            <item word="amazon" weight="1"></item>
        </state>
        
    </neuro_trigger>
    
    <neuro_trigger name="Type">
        
        <state name="SLR">
            <item word="SLR" weight="1"></item>
            <item word="DSLR" weight="1"></item>
            <item word="professional" weight="1"></item>
            <item word="pro" weight="1"></item>
        </state>
        
        <state name="Easy">
            <item word="Easy" weight="1"></item>
        </state>
        
        <state name="Semi Pro">
            <item word="semi" weight="1"></item>
            <item word="pro" weight="0.5"></item>
        </state>
        
    </neuro_trigger>
    
    <neuro_trigger name="Review">
        
        <state name="1">
            <item word="1" weight="1"></item>
            <item word="low" weight="1"></item>
        </state>
        
        <state name="2">
            <item word="2" weight="1"></item>
        </state>
        
        <state name="3">
            <item word="3" weight="1"></item>
            <item word="average" weight="1"></item>
        </state>
        
        <state name="4">
            <item word="4" weight="1"></item>
            <item word="good" weight="1"></item>
        </state>
        
        <state name="5">
            <item word="5" weight="1"></item>
            <item word="best" weight="1"></item>
        </state>
        
    </neuro_trigger>
    
    <neuro_trigger name="OnSale">
        <state name="True">
            <item word="on" weight="0.5"></item>
            <item word="sale" weight="0.5"></item>
        </state>
        
    </neuro_trigger>
    
</neuro_triggers>

