<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE neuro_triggers 
[
	<!ELEMENT neuro_triggers (neuro_trigger+)>
	<!ATTLIST neuro_triggers name CDATA #REQUIRED>
	<!ELEMENT neuro_trigger (state+)>
	<!ATTLIST neuro_trigger name CDATA #REQUIRED>
	<!ELEMENT state (item+)>
	<!ATTLIST state name CDATA #REQUIRED>
	<!ELEMENT item (#PCDATA)>
	<!ATTLIST item word CDATA #REQUIRED>
	<!ATTLIST item weight CDATA #REQUIRED>
]>

<neuro_triggers name="Personal">

	<neuro_trigger name="Friends">

		<state name="Victor">
      <item word="victor" weight="1.0"></item>
      <item word="yekelchik" weight="1.0"></item>
		</state>

		<state name="Rob">
			<item word="robert" weight="1.0"></item>
			<item word="rob" weight="1.0"></item>
			<item word="freidson" weight="1.0"></item>
		</state>

	</neuro_trigger>

	<neuro_trigger name="Topic">

		<state name="256gl">
			<item word="256gl" weight="1.0"></item>
		</state>

    <state name="Audio">
      <item word="audio" weight="1.0"></item>
    </state>

    <state name="Boards">
      <item word="boards" weight="1.0"></item>
      <item word="board" weight="1.0"></item>
    </state>

    <state name="Book">
      <item word="book" weight="1.0"></item>
    </state>

    <state name="Fun">
      <item word="fun" weight="1.0"></item>
    </state>

    <state name="Hackers">
      <item word="hackers" weight="1.0"></item>
    </state>

    <state name="Ideas">
      <item word="ideas" weight="1.0"></item>
      <item word="idea" weight="1.0"></item>
    </state>

    <state name="People">
      <item word="people" weight="1.0"></item>
    </state>

    <state name="MyNotes">
      <item word="my" weight="0.5"></item>
      <item word="notes" weight="0.5"></item>
      <item word="mynotes" weight="1.0"></item>
    </state>

    <state name="People">
      <item word="people" weight="1.0"></item>
    </state>

    <state name="Presentation">
      <item word="presentation" weight="1.0"></item>
      <item word="presentations" weight="1.0"></item>
    </state>

    <state name="Recepies">
      <item word="recepies" weight="1.0"></item>
      <item word="рецепты" weight="1.0"></item>
    </state>

    <state name="Sale">
      <item word="sale" weight="1.0"></item>
      <item word="sales" weight="1.0"></item>
    </state>
    
    <state name="Todo">
      <item word="todo" weight="1.0"></item>
      <item word="tо" weight="0.5"></item>
      <item word="do" weight="0.5"></item>
    </state>

	</neuro_trigger>

</neuro_triggers>

