<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE neuro_triggers 
[
	<!ELEMENT neuro_triggers (neuro_trigger+)>
	<!ATTLIST neuro_triggers name CDATA #REQUIRED>
	<!ELEMENT neuro_trigger (state+)>
	<!ATTLIST neuro_trigger name CDATA #REQUIRED>
	<!ELEMENT state (item+)>
	<!ATTLIST state name CDATA #REQUIRED>
	<!ATTLIST state discharge CDATA #IMPLIED>
	<!ELEMENT item (#PCDATA)>
	<!ATTLIST item word CDATA #REQUIRED>
	<!ATTLIST item weight CDATA #REQUIRED>
]>

<neuro_triggers name="Cars">

	<neuro_trigger name="Type">

		<state name="New">
			<item word="new" weight="1.0"></item>
		</state>

		<state name="Used">
			<item word="used" weight="1.0"></item>
			<item word="preowned" weight="1.0"></item>
		</state>

	</neuro_trigger>

	<neuro_trigger name="Year">

		<state name="2013">
			<item word="2013" weight="1"></item>
		</state>

		<state name="2012">
			<item word="2012" weight="1"></item>
		</state>

		<state name="2011">
			<item word="2011" weight="1"></item>
		</state>

		<state name="2010">
			<item word="2010" weight="1"></item>
		</state>

		<state name="2009">
			<item word="2009" weight="1"></item>
		</state>

		<state name="2008">
			<item word="2008" weight="1"></item>
		</state>

		<state name="2007">
			<item word="2007" weight="1"></item>
		</state>

		<state name="2006">
			<item word="2006" weight="1"></item>
		</state>

		<state name="2005">
			<item word="2005" weight="1"></item>
		</state>

		<state name="2004">
			<item word="2004" weight="1"></item>
		</state>

		<state name="2003">
			<item word="2003" weight="1"></item>
		</state>

		<state name="2002">
			<item word="2002" weight="1"></item>
		</state>

		<state name="2001">
			<item word="2001" weight="1"></item>
		</state>

	</neuro_trigger>

	<neuro_trigger name="Color">

		<state name="Black">
			<item word="black" weight="1"></item>
			<item word="ebony" weight="1"></item>
			<item word="nighthawk" weight="1"></item>
			<item word="graphite" weight="1"></item>
			<item word="черный" weight="1"></item>
			<item word="черная" weight="1"></item>
			<item word="черные" weight="1"></item>
		</state>

		<state name="Red">
			<item word="red" weight="1"></item>
			<item word="ruby" weight="1"></item>
			<item word="maroon" weight="1"></item>
			<item word="burgundy" weight="1"></item>
			<item word="merlot" weight="1"></item>
			<item word="красный" weight="1"></item>
			<item word="красная" weight="1"></item>
			<item word="красные" weight="1"></item>
		</state>

		<state name="White">
			<item word="white" weight="1"></item>
			<item word="diamond" weight="1"></item>
			<item word="opal" weight="1"></item>
			<item word="белый" weight="1"></item>
			<item word="белые" weight="1"></item>
			<item word="белая" weight="1"></item>
		</state>

		<state name="Beige">
			<item word="beige" weight="1"></item>
			<item word="sand" weight="1"></item>
		</state>

		<state name="Gray">
			<item word="gray" weight="1"></item>
			<item word="grey" weight="1"></item>
			<item word="granite" weight="1"></item>
			<item word="granit" weight="1"></item>
			<item word="серый" weight="1"></item>
			<item word="серые" weight="1"></item>
			<item word="серая" weight="1"></item>
		</state>

		<state name="Tan">
			<item word="tan" weight="1"></item>
		</state>

		<state name="Silver">
			<item word="silver" weight="1"></item>
			<item word="frost" weight="1"></item>
			<item word="серебристая" weight="1"></item>
			<item word="серебристые" weight="1"></item>
			<item word="асфальт" weight="1"></item>
		</state>

		<state name="Blue">
			<item word="blue" weight="1"></item>
			<item word="голубой" weight="1"></item>
			<item word="голубая" weight="1"></item>
			<item word="голубые" weight="1"></item>
			<item word="синий" weight="1"></item>
			<item word="синие" weight="1"></item>
			<item word="синяя" weight="1"></item>
		</state>

		<state name="Sage">
			<item word="sage" weight="1"></item>
		</state>

		<state name="Green">
			<item word="green" weight="1"></item>
			<item word="зеленый" weight="1"></item>
			<item word="зеленые" weight="1"></item>
			<item word="зеленая" weight="1"></item>
		</state>

		<state name="Pewter">
			<item word="pewter" weight="1"></item>
		</state>

		<state name="Flint">
			<item word="flint" weight="1"></item>
		</state>

	</neuro_trigger>

	<neuro_trigger name="Engine">

		<state name="4 cyl">
			<item word="4" weight="0.5"></item>
			<item word="cyl" weight="0.5"></item>
			<item word="cylinder" weight="0.5"></item>
			<item word="cylinders" weight="0.5"></item>
			<item word="v4" weight="1"></item>
			<item word="цилиндра" weight="0.5"></item>
			<item word="цилиндр" weight="0.5"></item>
		</state>

		<state name="5 cyl">
			<item word="5" weight="0.5"></item>
			<item word="cyl" weight="0.5"></item>
			<item word="cylinder" weight="0.5"></item>
			<item word="cylinders" weight="0.5"></item>
			<item word="цилиндров" weight="0.5"></item>
			<item word="цилиндр" weight="0.5"></item>
		</state>

		<state name="6 cyl">
			<item word="6" weight="0.5"></item>
			<item word="cyl" weight="0.5"></item>
			<item word="cylinder" weight="0.5"></item>
			<item word="cylinders" weight="0.5"></item>
			<item word="v6" weight="1"></item>
			<item word="цилиндров" weight="0.5"></item>
			<item word="цилиндр" weight="0.5"></item>
		</state>

		<state name="8 cyl">
			<item word="8" weight="0.5"></item>
			<item word="cyl" weight="0.5"></item>
			<item word="cylinder" weight="0.5"></item>
			<item word="cylinders" weight="0.5"></item>
			<item word="v8" weight="1"></item>
			<item word="цилиндров" weight="0.5"></item>
			<item word="цилиндр" weight="0.5"></item>
		</state>

	</neuro_trigger>

	<neuro_trigger name="Interior">

		<state name="Leather">
			<item word="leather" weight="1"></item>
			<item word="кожа" weight="1"></item>
			<item word="кожанные" weight="1"></item>
			<item word="кожанная" weight="1"></item>
		</state>

		<state name="Leatherette">
			<item word="leatherette" weight="1"></item>
		</state>

		<state name="Cloth">
			<item word="cloth" weight="1"></item>
			<item word="заменитель" weight="1"></item>
		</state>

	</neuro_trigger>

	<neuro_trigger name="Model">

		<state name="CSX">
			<item word="csx" weight="1"></item>
		</state>

		<state name="MDX">
			<item word="mdx" weight="1"></item>
		</state>

		<state name="RDX">
			<item word="rdx" weight="1"></item>
		</state>

		<state name="RL">
			<item word="rl" weight="1"></item>
		</state>

		<state name="TSX">
			<item word="tsx" weight="1"></item>
		</state>

		<state name="TL">
			<item word="tl" weight="1"></item>
		</state>

		<state name="CL">
			<item word="cl" weight="1"></item>
		</state>

		<state name="EL">
			<item word="el" weight="1"></item>
		</state>

		<state name="Integra">
			<item word="integra" weight="1"></item>
		</state>

		<state name="Legend">
			<item word="legend" weight="1"></item>
		</state>

		<state name="NSX">
			<item word="nsx" weight="1"></item>
		</state>

		<state name="NSX-T">
			<item word="nsx-t" weight="1"></item>
		</state>

		<state name="RSX">
			<item word="rsx" weight="1"></item>
		</state>

		<state name="Vigor">
			<item word="vigor" weight="1"></item>
		</state>

	</neuro_trigger>

	<neuro_trigger name="Make">

		<state name="Acura">
			<item word="acura" weight="1"></item>
			<item word="акура" weight="1"></item>
			<item word="акюра" weight="1"></item>
			<item word="акуры" weight="1"></item>
			<item word="акюры" weight="1"></item>
			<item word="اكورا" weight="1"></item>
			<item word="csx" weight="1"></item>
			<item word="mdx" weight="1"></item>
			<item word="rdx" weight="1"></item>
			<item word="rl" weight="1"></item>
			<item word="tsx" weight="1"></item>
			<item word="tl" weight="1"></item>
			<item word="cl" weight="1"></item>
			<item word="el" weight="1"></item>
			<item word="integra" weight="1"></item>
			<item word="legend" weight="1"></item>
			<item word="nsx" weight="1"></item>
			<item word="nsx-t" weight="1"></item>
			<item word="rsx" weight="1"></item>
			<item word="vigor" weight="1"></item>
		</state>

		<state name="Audi">
			<item word="audi" weight="1"></item>
			<item word="ауди" weight="1"></item>
			<item word="a3" weight="1"></item>
			<item word="a4" weight="1"></item>
			<item word="a5" weight="1"></item>
			<item word="a6" weight="1"></item>
			<item word="a8" weight="1"></item>
			<item word="q5" weight="1"></item>
			<item word="q7" weight="1"></item>
			<item word="r8" weight="1"></item>
			<item word="s4" weight="1"></item>
			<item word="s5" weight="1"></item>
			<item word="s6" weight="1"></item>
			<item word="s8" weight="1"></item>
			<item word="tt" weight="1"></item>
			<item word="tts" weight="1"></item>
		</state>

		<state name="BMW">
			<item word="bmw" weight="1"></item>
			<item word="бмв" weight="1"></item>
			<item word="series" weight="0.5"></item>
			<item word="1" weight="0.5"></item>
			<item word="3" weight="0.5"></item>
			<item word="5" weight="0.5"></item>
			<item word="6" weight="0.5"></item>
			<item word="7" weight="0.5"></item>
			<item word="m3" weight="1"></item>
			<item word="x3" weight="1"></item>
			<item word="x5" weight="1"></item>
			<item word="x6" weight="1"></item>
			<item word="z4" weight="1"></item>
		</state>

		<state name="American" >
			<item word="american" weight="1"></item>
			<item word="domestic" weight="1"></item>
			<item word="американская" weight="1"></item>
			<item word="американские" weight="1"></item>
		</state>

		<state name="European">
			<item word="european" weight="1"></item>
			<item word="import" weight="1"></item>
			<item word="европейские" weight="1"></item>
			<item word="европейская" weight="1"></item>
		</state>

		<state name="Japanese">
			<item word="japanese" weight="1"></item>
			<item word="import" weight="1"></item>
			<item word="японские" weight="1"></item>
			<item word="японская" weight="1"></item>
		</state>

		<state name="Korean">
			<item word="korean" weight="1"></item>
			<item word="корейская" weight="1"></item>
			<item word="корейские" weight="1"></item>
		</state>

		<state name="Cadillac">
			<item word="cadillac" weight="1"></item>
			<item word="cts" weight="1"></item>
			<item word="dts" weight="1"></item>
			<item word="escalade" weight="1"></item>
			<item word="srx" weight="1"></item>
			<item word="sts" weight="1"></item>
			<item word="xlr" weight="1"></item>
			<item word="кадилак" weight="1"></item>
			<item word="кадилаки" weight="1"></item>
		</state>

		<state name="Chevrolet">
			<item word="chevy" weight="1"></item>
			<item word="chevrolet" weight="1"></item>
			<item word="avalanche" weight="1"></item>
			<item word="aveo" weight="1"></item>
			<item word="camaro" weight="1"></item>
			<item word="cobalt" weight="1"></item>
			<item word="colorado" weight="1"></item>
			<item word="corvette" weight="1"></item>
			<item word="equinox" weight="1"></item>
			<item word="express" weight="1"></item>
			<item word="hhr" weight="1"></item>
			<item word="impala" weight="1"></item>
			<item word="malibu" weight="1"></item>
			<item word="silverado" weight="1"></item>
			<item word="suburban" weight="1"></item>
			<item word="tahoe" weight="1"></item>
			<item word="trailBlazer" weight="1"></item>
			<item word="traverse" weight="1"></item>
			<item word="uplander" weight="1"></item>
			<item word="шевроле" weight="1"></item>
		</state>

		<state name="Dodge">
			<item word="dodge" weight="1"></item>
			<item word="avenger" weight="1"></item>
			<item word="caliber" weight="1"></item>
			<item word="challenger" weight="1"></item>
			<item word="charger" weight="1"></item>
			<item word="dakota" weight="1"></item>
			<item word="durango" weight="1"></item>
			<item word="grand" weight="0.5"></item>
			<item word="caravan" weight="1"></item>
			<item word="journey" weight="1"></item>
			<item word="nitro" weight="1"></item>
			<item word="ram" weight="1"></item>
			<item word="sprinter" weight="1"></item>
			<item word="viper" weight="1"></item>
			<item word="додж" weight="1"></item>
			<item word="доджи" weight="1"></item>
		</state>

		<state name="Ford">
			<item word="ford" weight="1"></item>
			<item word="فورد" weight="1"></item>
			<item word="e-series" weight="1"></item>
			<item word="escape" weight="1"></item>
			<item word="expedition" weight="1"></item>
			<item word="explorer" weight="1"></item>
			<item word="f-150" weight="1"></item>
			<item word="f-250" weight="1"></item>
			<item word="f-350" weight="1"></item>
			<item word="f-450" weight="1"></item>
			<item word="flex" weight="1"></item>
			<item word="focus" weight="1"></item>
			<item word="fusion" weight="1"></item>
			<item word="mustang" weight="1"></item>
			<item word="ranger" weight="1"></item>
			<item word="shelby" weight="1"></item>
			<item word="gt500" weight="1"></item>
			<item word="taurus" weight="1"></item>
			<item word="transit" weight="1"></item>
			<item word="форд" weight="1"></item>
			<item word="форды" weight="1"></item>
			<item word="мустанг" weight="1"></item>
		</state>

		<state name="General Motors">
			<item word="gm" weight="1"></item>
			<item word="general" weight="1"></item>
			<item word="Mmotors" weight="1"></item>
			<item word="gmc" weight="1"></item>
		</state>

		<state name="Honda">
			<item word="honda" weight="1"></item>
			<item word="accord" weight="1"></item>
			<item word="civic" weight="1"></item>
			<item word="cr-v" weight="1"></item>
			<item word="element" weight="1"></item>
			<item word="fit" weight="1"></item>
			<item word="insight" weight="1"></item>
			<item word="odyssey" weight="1"></item>
			<item word="pilot" weight="1"></item>
			<item word="s2000" weight="1"></item>
			<item word="ridgeline" weight="1"></item>
			<item word="хонда" weight="1"></item>
			<item word="хонды" weight="1"></item>
		</state>

		<state name="Hyundai">
			<item word="hyundai" weight="1"></item>
			<item word="accent" weight="1"></item>
			<item word="azera" weight="1"></item>
			<item word="elantra" weight="1"></item>
			<item word="genesis" weight="1"></item>
			<item word="santa" weight="0.5"></item>
			<item word="fe" weight="0.5"></item>
			<item word="sonata" weight="1"></item>
			<item word="tiburon" weight="1"></item>
			<item word="tucson" weight="1"></item>
			<item word="veracruz" weight="1"></item>
		</state>

		<state name="Infiniti">
			<item word="infiniti" weight="1"></item>
			<item word="ex" weight="0.5"></item>
			<item word="fx" weight="1"></item>
			<item word="g" weight="1"></item>
			<item word="m" weight="1"></item>
			<item word="qx" weight="1"></item>
			<item word="инфинити" weight="1"></item>
		</state>

		<state name="Isuzu">
			<item word="isuzu" weight="1"></item>
			<item word="ascender" weight="0.5"></item>
			<item word="axiom" weight="1"></item>
			<item word="rodeo" weight="1"></item>
			<item word="i-280" weight="1"></item>
			<item word="i-290" weight="1"></item>
			<item word="i-350" weight="1"></item>
			<item word="Ii-370" weight="1"></item>
		</state>

		<state name="Jaguar">
			<item word="jaguar" weight="1"></item>
			<item word="xf" weight="1"></item>
			<item word="xj" weight="1"></item>
			<item word="xk" weight="1"></item>
			<item word="ягуар" weight="1"></item>
			<item word="ягуары" weight="1"></item>
		</state>

		<state name="Jeep">
			<item word="jeep" weight="1"></item>
			<item word="commander" weight="1"></item>
			<item word="compass" weight="1"></item>
			<item word="grand" weight="0.5"></item>
			<item word="cherokee" weight="1"></item>
			<item word="liberty" weight="1"></item>
			<item word="patriot" weight="1"></item>
			<item word="wrangler" weight="1"></item>
			<item word="джип" weight="1"></item>
			<item word="джипы" weight="1"></item>
		</state>

		<state name="Lincoln">
			<item word="lincoln" weight="1"></item>
			<item word="mks" weight="1"></item>
			<item word="mkt" weight="1"></item>
			<item word="mkx" weight="1"></item>
			<item word="mkz" weight="1"></item>
			<item word="navigator" weight="1"></item>
		</state>

		<state name="Lexus">
			<item word="Lexus" weight="1"></item>
			<item word="es" weight="1"></item>
			<item word="gs" weight="1"></item>
			<item word="gx" weight="1"></item>
			<item word="hs" weight="1"></item>
			<item word="ls" weight="1"></item>
			<item word="lx" weight="1"></item>
			<item word="rx" weight="1"></item>
			<item word="sc" weight="1"></item>
			<item word="лексус" weight="1"></item>
			<item word="лексусы" weight="1"></item>
		</state>

		<state name="Mazda">
			<item word="mazda" weight="1"></item>
			<item word="3" weight="0.5"></item>
			<item word="5" weight="0.5"></item>
			<item word="6" weight="0.5"></item>
			<item word="bseries" weight="1"></item>
			<item word="cx7" weight="1"></item>
			<item word="cx-9" weight="1"></item>
			<item word="mx-5" weight="1"></item>
			<item word="rx-8" weight="1"></item>
			<item word="tribute" weight="1"></item>
			<item word="мазда" weight="1"></item>
			<item word="мазды" weight="1"></item>
		</state>

		<state name="Mercedes-Benz">
			<item word="mercedes" weight="1"></item>
			<item word="benz" weight="1"></item>
			<item word="mclaren" weight="1"></item>
			<item word="slr" weight="1"></item>
			<item word="slk" weight="1"></item>
			<item word="sl" weight="1"></item>
			<item word="cls" weight="1"></item>
			<item word="clk" weight="1"></item>
			<item word="cl" weight="1"></item>
			<item word="class" weight="0.5"></item>
			<item word="мерс" weight="1"></item>
			<item word="мерседес" weight="1"></item>
			<item word="мерсы" weight="1"></item>
			<item word="мерседесы" weight="1"></item>
		</state>

		<state name="Nissan">
			<item word="nissan" weight="1"></item>
			<item word="350z" weight="1"></item>
			<item word="370z" weight="1"></item>
			<item word="armada" weight="1"></item>
			<item word="frontier" weight="1"></item>
			<item word="cube" weight="1"></item>
			<item word="gt-r" weight="1"></item>
			<item word="maxima" weight="1"></item>
			<item word="murano" weight="1"></item>
			<item word="pathfinder" weight="1"></item>
			<item word="quest" weight="1"></item>
			<item word="rogue" weight="1"></item>
			<item word="sentra" weight="1"></item>
			<item word="titan" weight="1"></item>
			<item word="versa" weight="1"></item>
			<item word="xterra" weight="1"></item>
		</state>

		<state name="Pontiac">
			<item word="Pontiac" weight="1"></item>
			<item word="g3" weight="1"></item>
			<item word="g5" weight="1"></item>
			<item word="g6" weight="1"></item>
			<item word="g8" weight="1"></item>
			<item word="montana" weight="1"></item>
			<item word="solstice" weight="1"></item>
			<item word="torrent" weight="1"></item>
			<item word="vibe" weight="1"></item>
		</state>

		<state name="Saturn">
			<item word="saturn" weight="1"></item>
			<item word="astra" weight="1"></item>
			<item word="aura" weight="1"></item>
			<item word="outlook" weight="1"></item>
			<item word="sky" weight="1"></item>
			<item word="vue" weight="1"></item>
		</state>

		<state name="Subaru">
			<item word="subaru" weight="1"></item>
			<item word="forester" weight="1"></item>
			<item word="impreza" weight="1"></item>
			<item word="legacy" weight="1"></item>
			<item word="outback" weight="1"></item>
			<item word="tribeca" weight="1"></item>
		</state>

		<state name="Mercury">
			<item word="mercury" weight="1"></item>
			<item word="mariner" weight="1"></item>
		</state>

		<state name="Scion">
			<item word="scion" weight="1"></item>
		</state>

		<state name="Toyota">
			<item word="toyota" weight="1"></item>
			<item word="4runner" weight="1"></item>
			<item word="avalon" weight="1"></item>
			<item word="camry" weight="1"></item>
			<item word="corolla" weight="1"></item>
			<item word="fj" weight="1"></item>
			<item word="cruiser" weight="1"></item>
			<item word="highlander" weight="1"></item>
			<item word="prius" weight="1"></item>
			<item word="rav4" weight="1"></item>
			<item word="sequoia" weight="1"></item>
			<item word="sienna" weight="1"></item>
			<item word="tacoma" weight="1"></item>
			<item word="tundra" weight="1"></item>
			<item word="venza" weight="1"></item>
			<item word="yaris" weight="1"></item>
			<item word="тойота" weight="1"></item>
			<item word="тойоты" weight="1"></item>
			<item word="камри" weight="1"></item>
			<item word="каролы" weight="1"></item>
			<item word="карола" weight="1"></item>
		</state>

		<state name="Volkswagen">
			<item word="volkswagen" weight="1"></item>
			<item word="golf" weight="1"></item>
			<item word="eos" weight="1"></item>
			<item word="gli" weight="1"></item>
			<item word="gti" weight="1"></item>
			<item word="jetta" weight="1"></item>
			<item word="beetle" weight="1"></item>
			<item word="passat" weight="1"></item>
			<item word="rabbit" weight="1"></item>
			<item word="routan" weight="1"></item>
			<item word="tiguan" weight="1"></item>
			<item word="touareg" weight="1"></item>
			<item word="фольксваген" weight="1"></item>
			<item word="фольксвагены" weight="1"></item>
		</state>

		<state name="Volvo">
			<item word="volvo" weight="1"></item>
			<item word="c30" weight="1"></item>
			<item word="c70" weight="1"></item>
			<item word="s40" weight="1"></item>
			<item word="s60" weight="1"></item>
			<item word="s80" weight="1"></item>
			<item word="v50" weight="1"></item>
			<item word="v70" weight="1"></item>
			<item word="xc60" weight="1"></item>
			<item word="xc70" weight="1"></item>
			<item word="xc90" weight="1"></item>
			<item word="вольво" weight="1"></item>
		</state>

		<state name="Mini">
			<item word="mini" weight="1"></item>
			<item word="cooper" weight="1"></item>
		</state>

	</neuro_trigger>

	<neuro_trigger name="Body">

		<state name="CargoVan">
			<item word="cargo" weight="1"></item>
			<item word="van" weight="1"></item>
		</state>

		<state name="Convertible">
			<item word="convertible" weight="1"></item>
			<item word="кабриолет" weight="1"></item>
			<item word="кабриолеты" weight="1"></item>
		</state>

		<state name="Coupe">
			<item word="coupe" weight="1"></item>
		</state>

		<state name="Hatchback">
			<item word="hatchback" weight="1"></item>
			<item word="hatch" weight="1"></item>
			<item word="горбатый" weight="1"></item>
			<item word="горбатые" weight="1"></item>
		</state>

		<state name="MiniVan">
			<item word="minivan" weight="1"></item>
			<item word="mini" weight="0.5"></item>
			<item word="van" weight="0.5"></item>
		</state>

		<state name="Truck">
			<item word="pick-up" weight="1"></item>
			<item word="trucks" weight="1"></item>
			<item word="truck" weight="1"></item>
			<item word="pick" weight="0.5"></item>
			<item word="up" weight="0.5"></item>
			<item word="грузовик" weight="1"></item>
			<item word="грузовики" weight="1"></item>
		</state>

		<state name="Sedan">
			<item word="sedan" weight="1"></item>
			<item word="sedans" weight="1"></item>
			<item word="седан" weight="1"></item>
			<item word="седаны" weight="1"></item>
		</state>

		<state name="Sport Utility">
			<item word="sport" weight="0.5"></item>
			<item word="utility" weight="1"></item>
			<item word="suv" weight="1"></item>
			<item word="suvs" weight="1"></item>
			<item word="спортивная" weight="1"></item>
			<item word="внедорожник" weight="1"></item>
			<item word="внедорожники" weight="1"></item>
		</state>

		<state name="Wagon">
			<item word="wagon" weight="1"></item>
			<item word="wagons" weight="1"></item>
		</state>

	</neuro_trigger>

	<neuro_trigger name="Hybrid">

		<state name="Hybrid">
			<item word="hybrid" weight="1.0"></item>
			<item word="hibrid" weight="1.0"></item>
			<item word="гибридная" weight="1"></item>
			<item word="гибридные" weight="1"></item>
		</state>

		<state name="Not Hybrid">
			<item word="hybrid" weight="0.6"></item>
			<item word="not" weight="0.6"></item>
		</state>

	</neuro_trigger>

	<neuro_trigger name="DriveTrain">

		<state name="AWD">
			<item word="4wd" weight="1.0"></item>
			<item word="awd" weight="1"></item>
			<item word="all" weight="0.5"></item>
			<item word="wheel" weight="0.4"></item>
			<item word="drive" weight="0.4"></item>
			<item word="4" weight="0.5"></item>
		</state>

		<state name="FWD">
			<item word="fwd" weight="1.0"></item>
			<item word="front" weight="0.5"></item>
			<item word="wheel" weight="0.4"></item>
			<item word="drive" weight="0.4"></item>
		</state>

		<state name="RWD">
			<item word="rwd" weight="1.0"></item>
			<item word="rear" weight="0.5"></item>
			<item word="wheel" weight="0.4"></item>
			<item word="drive" weight="0.4"></item>
		</state>

	</neuro_trigger>

	<neuro_trigger name="Transmission">

		<state name="Automatic">
			<item word="Automatic" weight="1.0"></item>
			<item word="Auto" weight="1.0"></item>
			<item word="автоматик" weight="1"></item>
			<item word="автоматическая" weight="1"></item>
			<item word="автоматические" weight="1"></item>
		</state>

		<state name="Manual">
			<item word="manual" weight="1.0"></item>
			<item word="transmission" weight="0.6"></item>
			<item word="ручная" weight="1"></item>
			<item word="ручные" weight="1"></item>
			<item word="ручник" weight="1"></item>
			<item word="ручной" weight="1"></item>
		</state>

	</neuro_trigger>

	<neuro_trigger name="Certified">

		<state name="Certified">
			<item word="certified" weight="1.0"></item>
		</state>

		<state name="Not Certified">
			<item word="certified" weight="0.6"></item>
			<item word="not" weight="0.6"></item>
		</state>

	</neuro_trigger>

	<neuro_trigger name="Mileage">

		<state name="Low">
			<item word="low" weight="0.7"></item>
			<item word="mileage" weight="0.5"></item>
			<item word="milage" weight="0.5"></item>
			<item word="miles" weight="0.5"></item>
		</state>

		<state name="High">
			<item word="high" weight="0.5"></item>
			<item word="mileage" weight="0.5"></item>
			<item word="milage" weight="0.5"></item>
			<item word="miles" weight="0.5"></item>
		</state>

		<state name="Average">
			<item word="average" weight="0.5"></item>
			<item word="mileage" weight="0.5"></item>
			<item word="milage" weight="0.5"></item>
			<item word="miles" weight="0.5"></item>
		</state>

	</neuro_trigger>

</neuro_triggers>

