<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE neuro_triggers 
[
	<!ELEMENT neuro_triggers (neuro_trigger+)>
	<!ATTLIST neuro_triggers name CDATA #REQUIRED>
	<!ELEMENT neuro_trigger (state+)>
	<!ATTLIST neuro_trigger name CDATA #REQUIRED>
	<!ELEMENT state (item+)>
	<!ATTLIST state name CDATA #REQUIRED>
	<!ATTLIST state discharge CDATA #IMPLIED>
	<!ELEMENT item (#PCDATA)>
	<!ATTLIST item word CDATA #REQUIRED>
	<!ATTLIST item weight CDATA #REQUIRED>
]>

<neuro_triggers name="Generic">

	<neuro_trigger name="Clause">
		<state name="Question">
			<item word="who" weight="1.0"></item>
			<item word="whom" weight="1.0"></item>
			<item word="whose" weight="1.0"></item>
			<item word="what" weight="1.0"></item>
			<item word="which" weight="1.0"></item>
			<item word="when" weight="1.0"></item>
			<item word="where" weight="1.0"></item>
			<item word="why" weight="1.0"></item>
			<item word="how" weight="1.0"></item>
			<item word="?" weight="1.0"></item>
		</state>
		<state name="Declarative" discharge="300">
			<item word="." weight="1.0"></item>
		</state>
		<state name="Enter">
			<item word="*enter*" weight="1.0"></item>
		</state>
	</neuro_trigger>

	<neuro_trigger name="Question">
		<state name="Who">
			<item word="who" weight="1.0"></item>
			<item word="whom" weight="1.0"></item>
			<item word="whose" weight="1.0"></item>
		</state>
		<state name="What">
			<item word="what" weight="1.0"></item>
			<item word="which" weight="1.0"></item>
		</state>
		<state name="When">
			<item word="when" weight="1.0"></item>
		</state>
		<state name="Where">
			<item word="where" weight="1.0"></item>
		</state>
		<state name="Why">
			<item word="why" weight="1.0"></item>
		</state>
		<state name="How">
			<item word="how" weight="1.0"></item>
		</state>
	</neuro_trigger>

  <neuro_trigger name="Reset">
    <state name="Reset">
      <item word="reset" weight="1.0"></item>
    </state>
  </neuro_trigger>

</neuro_triggers>

